apiVesrion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment lables
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set to create pod replicas, this should pod labels
  selectors:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  # This is pod defination
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
  spec:
    containers:
    - name: mongodb
      image: harshavardhan247/mongodb:v1

---
apiVersion: v1
kind: service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
